[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "22.0.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"

  