backend:
  name: github
  repo: askiya/WEBSITE-BUMDES-DESA-SALEv10 # ganti dengan repo kamu
  branch: main
  auth_type: implicit
  app_id: 9d97b081a2a8a1b13e48 # ini ID untuk Netlify CMS GitHub OAuth

media_folder: "public/uploads" # tempat gambar disimpan di repo
public_folder: "/uploads" # path publik yang diakses oleh website

collections:
  - name: "home"
    label: "Halaman Utama"
    files:
      - file: "src/mock/homeContent.json"
        label: "Konten Halaman Utama"
        name: "homeContent"
        fields:
          - { label: "Judul Hero", name: "title", widget: "string" }
          - { label: "Subjudul", name: "subtitle", widget: "text" }
          - { label: "Tagline", name: "tagline", widget: "string" }

  - name: "tentang"
    label: "Halaman Tentang"
    folder: "src/content/tentang"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi", name: "body", widget: "markdown" }
